name: Validar SKUs en Google Sheets

on:
  workflow_dispatch: 

jobs:
  validar_modelos:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4 # Actualizado a la última versión

      - name: Instalar Python
        uses: actions/setup-python@v5 # Actualizado a la última versión
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install -r requirements.txt

      - name: Ejecutar búsqueda y actualizar Sheets
        run: python scraper.py
